# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wc2PA1KTmHUC1J2k7upYvGz9Enu9QRbW
"""



num= input('Number of elements in array')
N= int(num)
X=[]
Y=[]
Z=[]

a = input('Enter elements of a list separated by space ')
print("\n")
X = a.split()
for i in range(0,N):
  X[i]=int(X[i])
for i in range(0,N):
  Y.append(X[N-i-1])
for i in range(0,N):
  y= X[i]*Y[i]
  Z.append(y)

print(*Z)

"""Q2"""

num= input('Number of elements in array')
N= int(num)
A=[]
m1=0
m2=0

a = input('Enter elements of a list separated by space ')
print("\n")
A = a.split()
for i in range(0,N):
    A[i]=int(A[i])
for i in range(0,N):
    if m1>A[i]:
        m2=m1
        m1=A[i]
    else:
        m1=m1
        
min1=A[0]
min2=A[0]
for i in range(0,N):
    if min1<A[i]:
        min2=min1
        min1=A[i]
    else:
        min1=min1
        
print(m2,' ',min2)

num= input('Number of elements in array')
N= int(num)
A=[]


a = input('Enter elements of a list separated by space ')
print("\n")
A = a.split()
for i in range(0,N):
    A[i]=int(A[i])
for i in range(0,N):
    if(A[i]%5==0):
        A[i]=A[i]
    else:
        print(A[i],end=' ')

n= input('Number of bits in binary')
N= int(n)
A=[]
count0=0
count1=0
a = input('Enter elements of a list separated by space ')
print("\n")
A = a.split()
for i in range(0,N):
    A[i]=int(A[i])
for i in range(0,N):
    if A[i]==0 or A[i]==1:
        A[i]=A[i]
    else:
        print('Error! Invalid Values entered!')
        
for i in range(0,N):
    if A[i]==0:
        count0=count0+1
    else:
        count1=count1+1
if count0==1 or count1 == 1:
    print('YES')
else:
    print('NO')

n= input('Enter Number')
N= int(n)
fact=1
for i in range(1,N+1):
    fact=fact*i
print(fact)

n= input('Enter lower limit')
N= int(n)

m= input('Enter upper limit')
M= int(m)

for i in range (N,M+1):
    c=i
    while c!=0:
        if c%2==0:
            if c<10:
                print(i, end=',')
                c=0
            else :
                c=c/10
        else:
            c=0